package eu.x_road.emta_v6;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2018-08-26T16:09:41.026+03:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "xteeFieAndmed", 
                  wsdlLocation = "classpath:xteeFieAndmed.wsdl",
                  targetNamespace = "http://emta-v6.x-road.eu") 
public class XteeFieAndmed_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://emta-v6.x-road.eu", "xteeFieAndmed");
    public final static QName XteeFieAndmedSOAP = new QName("http://emta-v6.x-road.eu", "xteeFieAndmedSOAP");
    static {
        URL url = XteeFieAndmed_Service.class.getClassLoader().getResource("xteeFieAndmed.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(XteeFieAndmed_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:xteeFieAndmed.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public XteeFieAndmed_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public XteeFieAndmed_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XteeFieAndmed_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public XteeFieAndmed_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public XteeFieAndmed_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public XteeFieAndmed_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WebServiceInterface
     */
    @WebEndpoint(name = "xteeFieAndmedSOAP")
    public WebServiceInterface getXteeFieAndmedSOAP() {
        return super.getPort(XteeFieAndmedSOAP, WebServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceInterface
     */
    @WebEndpoint(name = "xteeFieAndmedSOAP")
    public WebServiceInterface getXteeFieAndmedSOAP(WebServiceFeature... features) {
        return super.getPort(XteeFieAndmedSOAP, WebServiceInterface.class, features);
    }

}
