
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package eu.x_road.emta_v6;

import java.awt.*;
import java.util.List;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2018-08-26T16:09:40.915+03:00
 * Generated source version: 3.2.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "xteeFieAndmed",
                      portName = "xteeFieAndmedSOAP",
                      targetNamespace = "http://emta-v6.x-road.eu",
                      wsdlLocation = "classpath:xteeFieAndmed.wsdl",
                      endpointInterface = "eu.x_road.emta_v6.WebServiceInterface")
                      
public class XteeFieAndmedSOAPImpl implements WebServiceInterface {

    private static final Logger LOG = Logger.getLogger(XteeFieAndmedSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see eu.x_road.emta_v6.WebServiceInterface#xteeFieAndmed(eu.x_road.emta_v6.PersonalIdentityCode keha, eu.x_road.xsd.identifiers.XRoadClientIdentifierType client, eu.x_road.xsd.identifiers.XRoadServiceIdentifierType service, java.lang.String id, java.lang.String protocolVersion, java.lang.String userId, java.lang.String issue, eu.x_road.emta_v6.XteeFieAndmedResponseType paring)*
     */
    public void xteeFieAndmed(javax.xml.ws.Holder<PersonalIdentityCode> keha, javax.xml.ws.Holder<eu.x_road.xsd.identifiers.XRoadClientIdentifierType> client, javax.xml.ws.Holder<eu.x_road.xsd.identifiers.XRoadServiceIdentifierType> service, javax.xml.ws.Holder<java.lang.String> id, javax.xml.ws.Holder<java.lang.String> protocolVersion, javax.xml.ws.Holder<java.lang.String> userId, javax.xml.ws.Holder<java.lang.String> issue, javax.xml.ws.Holder<XteeFieAndmedResponseType> paring) { 
        LOG.info("Executing operation xteeFieAndmed");
        try {
            keha.value.setIsikukood("Sai muudetud!");
            eu.x_road.emta_v6.XteeFieAndmedResponseType paringValue =
                    new eu.x_road.emta_v6.XteeFieAndmedResponseType();

            paringValue.setLisainfo("Andmed!");
            paringValue.setKokku("Midagi siia?");

            XteeFieAndmedResponseType.FieJada fieJada = new XteeFieAndmedResponseType.FieJada();
            List<SelfEmployedPerson> list = fieJada.getItem();

            SelfEmployedPerson selfEmployedPerson = new SelfEmployedPerson();
            selfEmployedPerson.setIsikukood(keha.value.getIsikukood());
            selfEmployedPerson.setAlgus("pp.kk.aaaa");
            selfEmployedPerson.setLopp("pp.kk.aaaa");
            list.add(selfEmployedPerson);

            paringValue.setFieJada(fieJada);
            paring.value = paringValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
